export const LoginConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
};
export const LogoutContant = "LOGOUT_SUCCESS";

export const PopularConstant = {
  POPULAR_REQUEST: "POPULAR_REQUEST",
  POPULAR_SUCCESS: "POPULAR_SUCCESS",
  POPULAR_ERROR: "POPULAR_ERROR",
};
export const ExploreConstant = {
  EXPLORE_REQUEST: "EXPLORE_REQUEST",
  EXPLORE_SUCCESS: "EXPLORE_SUCCESS",
  EXPLORE_ERROR: "EXPLORE_ERROR",
};
export const FeaturedConstant = {
  FEATURED_REQUEST: "FEATURED_REQUEST",
  FEATURED_SUCCESS: "FEATURED_SUCCESS",
  FEATURED_ERROR: "FEATURED_ERROR",
};
